# ==========================================================
# Hex Status 2.0 - Configuration File
# ==========================================================

# Authentication
# --------------
auth:
  key: "Your license Key"  # Your license key

# Application Settings
# -------------------
app:
  name: "Hex Status"             # Application name displayed in UI
  port: 3000                     # Port to run the web server on
  refreshInterval: 5000          # Monitoring refresh in milliseconds

# Monitoring Settings
# ------------------
monitoring:
  pingTimeout: 3000              # Timeout for ping requests in ms
  maxHistoryPoints: 100          # Maximum datapoints to store per service
  healthCheckInterval: 5000      # Health check interval in ms

# Discord Integration
# ------------------
discord:
  enabled: true                  # Enable Discord integration
  token: "Your Discord Bots Token"    # Discord bot token
  channelId: "Your Channel ID"   # Channel ID for status updates
  thumbnail: "https://img.hexrift.net/HS.png"  # Thumbnail image URL
  image: "https://img.hexrift.net/Banner.png"  # Image URL
  updateInterval: 10000          # Updates every 10 seconds

# Analytics Configuration
# ----------------------
analytics:
  google:
    enabled: true
    tracking_id: "Your Google Tracking ID"  # Google Analytics tracking ID

# Services to Monitor
# ------------------
services:
  - name: "Website"
    url: "https://hexrift.net"
    category: "Store"
    
  - name: "Forum"
    url: "https://forum.hexrift.net"
    category: "Application Forum"

  - name: "Track"
    url: "https://track.hexrift.net"
    category: "Bug Tracker"

  - name: "Auth"
    url: "https://dash.hexrift.net"
    category: "Hex License Dashboard"

  - name: "Share"
    url: "https://share.hexrift.net"
    category: "File Share"

  - name: "API"
    url: "https://api.hexrift.net"
    category: "Hex License API"

    
# Footer
# ------
footer:
  copyright: "Hex Status"        # Copyright text in footer
