app:
  name: "Hex Status"
  port: 3000
  refreshInterval: 5000  # Status check interval in milliseconds

monitoring:
  pingTimeout: 3000
  maxHistoryPoints: 100
  healthCheckInterval: 5000

discord:
  token: "MTMyNjc3MDc0MTE0MzY2NjcyOQ.GFGsTf.iBzSXQezyI31Dz4I62e38yaHFPgZuyrSmulF_A"
  channelId: "1342463374692188310"
  thumbnail: "https://hexarion.net/Hex-Status.png"
  updateInterval: 10000  # Updates every 30 seconds


services:
  - name: "Website"
    url: "hexarion.net"
    category: "Internal"
    
  - name: "Forum"
    url: "forum.hexarion.net"
    category: "Internal"

  - name: "Track"
    url: "track.hexarion.net"
    category: "Internal"

  - name: "Dashboard"
    url: "dash.hexarion.net"
    category: "Internal"

  - name: "Share"
    url: "share.hexarion.net"
    category: "Internal"

  - name: "Auth"
    url: "api.hexarion.net"
    category: "API"
footer:
  copyright: "Hex Status"
  version: "1.0.0"
