server:
  port: 3001
  host: 'localhost'
  env: 'development'
  baseUrl: 'http://localhost:3001'
  
sendgrid:
  templates:
    contactForm: 'd-xxxxxxxxxxxxxxxxxxxxxxxx'
    statusAlert: 'd-xxxxxxxxxxxxxxxxxxxxxxxx'
  from:
    email: 'updates@hexstatus.com'
    name: 'Hex Status'
  settings:
    alertFrequency: 'immediate'
    batchSize: 1000

services:
  - name: 'API Server'
    url: 'https://api.hexarion.net'
  - name: 'Website'
    url: 'https://hexarion.net'
  - name: 'Database'
    url: 'https://auth.hexarion.net'

admin:
  email: 'admin@hexstatus.com'

footer:
  copyright: 'Hex Status. All rights reserved.'
  links:
    - text: 'Privacy Policy'
      url: '/privacy-policy'
    - text: 'Terms of Service'
      url: '/terms-of-service'
    - text: 'Contact'
      url: '/contact'

legal:
  privacyPolicy:
    title: 'Privacy Policy'
    lastUpdated: '2023-12-01'
    sections:
      - heading: 'Information We Collect'
        content: 'We collect information that you provide directly to us...'
      - heading: 'How We Use Your Information'
        content: 'We use the information we collect to provide and improve our services...'

  termsOfService:
    title: 'Terms of Service'
    lastUpdated: '2023-12-01'
    sections:
      - heading: 'Agreement to Terms'
        content: 'By accessing our service, you agree to be bound by these terms...'
      - heading: 'Use License'
        content: 'Permission is granted to temporarily download one copy of the materials...'

theme:
  primary: '#00ff00'
  secondary: '#00cc00'
  dark:
    background: '#121212'
    paper: '#1E1E1E'
  light:
    background: '#f8f9fa'
    paper: '#ffffff'

features:
  realTimeUpdates: true
  emailAlerts: true
  pushNotifications: true
  darkMode: true

ui:
  maxWidth: 1440
  cardRadius: 12
  animation:
    duration: 300

discord:
  token: ''
  clientId: '1327147372081447024'
  guildId: '1323896546538033233'
  settings:
    urls:
      thumbnail: 'https://hexarion.net/Hex-Status.png'
    site:
      footer: 'Hex Status'
    system:
      refresh_interval: 5000
