app:
  name: "Hex Status"
  port: 3000
  refreshInterval: 5000  

database:
  url: "mongodb://localhost/hex-status"

monitoring:
  pingTimeout: 3000
  maxHistoryPoints: 100
  healthCheckInterval: 5000

discord:
  token: "MTMyNjc3MDc0MTE0MzY2NjcyOQ.GFGsTf.iBzSXQezyI31Dz4I62e38yaHFPgZuyrSmulF_A"
  channelId: "1342463374692188310"
  thumbnail: "https://hexarion.net/Hex-Status.png"
  updateInterval: 10000 

services:
  - name: "Website"
    url: "hexarion.net"
    category: "Store"
    
  - name: "Forum"
    url: "forum.hexarion.net"
    category: "Suggestion Forum"

  - name: "Track"
    url: "track.hexarion.net"
    category: "Bug Tracker"

  - name: "Dashboard"
    url: "dash.hexarion.net"
    category: "Auth Dashboard"

  - name: "Share"
    url: "share.hexarion.net"
    category: "File Share"

  - name: "Auth"
    url: "api.hexarion.net"
    category: "Auth API"

footer:
  copyright: "Hex Status"
  version: "1.0.0"
